name: Build CI

on:
  push:
    branches:
      - main
jobs: 
  build-frontend:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4.2.2
      - name: ls
        run: ls
      - name: build react image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react:v1 frontend/.
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push react 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react:v1
          
